spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: pass
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
  flyway:
    baseline-on-migrate: true
    
